[phases.setup]
nixPkgs = ["nodejs_18", "pnpm"]

[phases.install]
cmds = ["pnpm i --frozen-lockfile"]

[phases.build]
cmds = ["cd server && node build.cjs"]

[start]
cmd = "node server/dist/index.js"

