[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["npm install -g pnpm", "export PATH=$PATH:/usr/local/bin && pnpm i --frozen-lockfile"]

[phases.build]
cmds = ["cd server && node build.cjs"]

[start]
cmd = "node server/dist/index.js"

