[providers]
node = "18"

[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["npm install -g pnpm", "pnpm i --frozen-lockfile"]

[phases.build]
cmds = ["cd server && node build.cjs"]

[start]
cmd = "node dist/index.js"

